postgresql:
  image: sameersbn/postgresql:9.6-4
  environment:
    - DB_USER=redmine
    - DB_PASS=password
    - DB_NAME=redmine_production
  volumes:
    - ./postgresql.conf.sample:/usr/share/postgresql/9.6/postgresql.conf.sample
redmine:
  image: sameersbn/redmine:3.4.6
  links:
    - postgresql:postgresql
  environment:
    - REDMINE_PORT=10083
  ports:
    - "10083:80"
